version: '3.8'

networks:
  reverse-proxy:
    name: reverse-proxy

services:
  nginx:
    image: nginx:1.24
    container_name: nginx
    volumes:
      - "./nginx:/etc/nginx/conf.d/"
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - reverse-proxy