global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alert.rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alert-manager:9093']

scrape_configs:
  - job_name: aggregated-trace-metrics
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: postgres-exporter
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']